### ISSUE TITLE
Subclass replaced with null

### ISSUE THREAD

**Issue by JFronny** [shedaniel/AutoConfig#11]
In one of the categories of my config there is an entry consisting of a custom class that I would like to pass a parameter to:
```
public Boolean enabled = true;

@Comment("An angel block (a block you can place in mid-air)")
@ConfigEntry.Gui.CollapsibleObject
public AngelBlock angelBlock = new AngelBlock(enabled);

public static class AngelBlock {
    public AngelBlock(boolean enabled) {
        this.enabled = enabled;
    }
    public Boolean enabled = true;
    @Comment("The distance to place the block at when placed in mid-air")
    @ConfigEntry.BoundedDiscrete(max = 10, min = 0)
    public Integer placeDistance = 3;
}
```
The config can be set from within the game and is properly serialized but when I restart the game and read the config the angelBlock field gets replaced with null, causing a NPE in my code and making the field practically useless as I would have to reset it on every restart.
When I remove the parameter and the initializer in the AngelBlock config class it works again

**Comment by shedaniel** [comment]
every constructor has to not have any parameters, you can have a separate class that extends AngelBlock to set the variable.
