### ISSUE TITLE
Custom Datatypes for lists don't get saved.

### ISSUE THREAD

**Issue by Geometrically** [shedaniel/AutoConfig#12]
When editing a List of custom objects as shown below, they get parsed correctly, but when editing them in the GUI config they are not saved.

```java
private final List<PairOfInts> complexList = Arrays.asList(new PairOfInts(0, 1), new PairOfInts(3, 7));

private static class PairOfInts {
        private int foo;
        private int bar;

        PairOfInts() {
            this(1, 2);
        }

        PairOfInts(int foo, int bar) {
            this.foo = foo;
            this.bar = bar;
        }
    }
```

**Comment by charlyb01** [comment]
And if you changed it from the config file directly, it will erase the new value with default ones...
There is an example is the mod that does it (the exact same code shown here) and it doesn't work so I don't get why it's in example. Really sad it doesn't work...
