### ISSUE TITLE
Crash when trying to read config

### ISSUE THREAD

**Issue by Mantarri** [shedaniel/AutoConfig#17]
When I try to read my config with
`ModConfig config = AutoConfig.getConfigHolder(ModConfig.class).getConfig();`

I get a crash when trying to start Minecraft [log](https://hastebin.com/yenubujewa.cs)

I do register the config in my mod's `onInitialize` method.

`AutoConfig.register(ModConfig.class, Toml4jConfigSerializer::new);`

**Comment by shedaniel** [comment]
You are using getConfigHolder before register

**Comment by Mantarri** [comment]
What could cause that though? I try to read the config in a Mixin to the`register` method in`Items`, and I register the config in my Mod's `onInitialize`, so the config should be registered before that Mixin is even loaded, if I understand how this works correctly.

**Comment by shedaniel** [comment]
Items register is done before mod init

**Comment by Mantarri** [comment]
Ah, that explains it.
Is there some way to open the config at that point then? If I'm correct, I _could_ just register it there, but I assume that doing it there isn't the best idea.

**Comment by shedaniel** [comment]
you could unify the get config method with register, with a boolean flag to know if it has been registered, if not, register it before getting the config object
