### ISSUE TITLE
Deprecated ModMenu Stuff

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [shedaniel/AutoConfig#30]
This is put in logs:

`[main/WARN]: WARNING! Mod autoconfigtoml is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.`

`[main/WARN]: WARNING! Mod autoconfig1u is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.`

**Comment by shedaniel** [comment]
No

**Comment by DragonEggBedrockBreaking** [comment]
> No

Can you explain further?
