### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Bendimester23** [shedaniel/AutoConfig#31]
[latest.log](https://github.com/shedaniel/AutoConfig/files/6211836/latest.log)
This happens, when i try to launch minecraft

**Comment by Bendimester23** [comment]
[message.txt](https://github.com/shedaniel/AutoConfig/files/6211844/message.txt)
forgot to add the crash

**Comment by Bendimester23** [comment]
Nvm, it was an issue with an older config, deleting solved it

**Comment by Leomacchia** [comment]
Sorry, I'm having the same exact issue with autoconfig1u, but I really can't find what I must delete... Could you help me? I'm getting crazy with this mod

**Comment by Bendimester23** [comment]
it was an old config, i just deleted some configs and it worked
