### ISSUE TITLE
Some entries don't save to the config file using AutoConfig

### ISSUE THREAD

**Issue by Azagwen** [shedaniel/AutoConfig#35]
my AutoConfig code :
```java
@Config(name = AdbMain.ADB_NAMESPACE)
@Background(value = AdbMain.ADB_NAMESPACE + ":textures/gui/config_background.png")
public class AdbAutoConfig implements ConfigData {

    public enum StructureVoidRenderMode {
        PARTICLE,
        BOX_OUTLINE;
    }

    @Tooltip(count = 11)
    @EnumHandler(option = EnumHandler.EnumDisplayOption.BUTTON)
    public StructureVoidRenderMode struct_void_render = StructureVoidRenderMode.PARTICLE;

    @CollapsibleObject(startExpanded = true)
    public static StructVoidBoxColor box_color = new StructVoidBoxColor();

    public static class StructVoidBoxColor {
        @BoundedDiscrete(min = 0, max = 255)
        public int box_color_red = 64;

        @BoundedDiscrete(min = 0, max = 255)
        public int box_color_green = 255;

        @BoundedDiscrete(min = 0, max = 255)
        public int box_color_blue = 230;
    }
}
```
and the serializer I use from my Mod's main class :
```java
[ ... ]
@Override
public void onInitialize() {
	AutoConfig.register(AdbAutoConfig.class, GsonConfigSerializer::new);
}
```

None of the values set to `box_color` in GUI are ever saved to the file at all on my end, despite everything I tried.
Could I get any help if I did anything wrong ?
Or if I didn't, how long would it take to fix it ?

**Comment by shedaniel** [comment]
no static fields

**Comment by Azagwen** [comment]
> no static fields

well then how do I call these in a static context ?
I can't currently use them if they are not static.

**Comment by shedaniel** [comment]
please read the wiki

**Comment by Azagwen** [comment]
> please read the wiki

What am I looking for there ?
I did read it before posting my issue, I read every page of the Wiki related to AutoConfig closely, and nothing mentioned that static entries aren't saved properly.

**Comment by Azagwen** [comment]
> > please read the wiki
> 
> What am I looking for there ?
> I did read it before posting my issue, I read every page of the Wiki related to AutoConfig closely, and nothing mentioned that static entries aren't saved properly.

wait I just remebered I can do 
```java
AutoConfig.getConfigHolder(AdbAutoConfig.class).getConfig().myStuff ...
```
Sorry for bothering you !
