### ISSUE TITLE
Modrinth Availability

### ISSUE THREAD

**Issue by BattleCh1cken** [shedaniel/AutoConfig#42]
It would be nice to have this mod available on Modrinth, an alternative to Curseforge. Their API is much more open, allowing for better 3rd party tools for server hosting, as well as 3rd party clients, and better distribution of modpacks.

**Comment by rdrpenguin04** [comment]
Most shedaniel mods are on Modrinth; the only reason I could think of this not being there already is because it's falling dormant. The last commit was five months ago.

**Comment by shedaniel** [comment]
Please, stop making issues about it, this is annoying. Mods that make sense to be on modrinth are on modrinth.
