### ISSUE TITLE
Details for config files (not GUI) in the docs plzzz

### ISSUE THREAD

**Issue by Kouchya** [shedaniel/AutoConfig#43]
The current documentation seems to mention too few about config **files**. It's clear that we are using AutoConfig for creating configurations, not for just creating configuration **GUIs**. In my case, I was trying to create a multi-line comment for an entry in my mod's config file (not GUI!!!). I went through your whole wiki, only to find a `@Comment` annotation to create single-line comments in config files. There's literally NOTHING else mentioned about a config file, except for some user saving stuffs when interacting with a config GUI.

I finally figured out - on my own, with no help from the doc - that you can use a `\n` in the `@Comment` string to auto generate a multiline comment. Since it's a rare case to use a `\n` to split the text in Minecraft environment (or why is there the Iceberg mod? ), the solution didn't come to my mind that early. Before I found this very solution, I tried lots of workarounds like multiple `@Comment` annotations (compilation error of course). I even tried the `@ConfigEntry.Gui.Tooltip` annotation, and you can imagine how disappointed I was to find out it deals nothing with comments in config files. I think these are all important details that need to be added to the doc, unless you finally decide to change that introduction from `Annotation based API for mod configs` to `Annotation based API for mod config GUIs`.

**Comment by Kouchya** [comment]
Along with a lot more:
- Is there a way to insert an extra empty line after each entry in the config file? If not, it's a highly recommended feature now.
- The multiline comment looks so ugly like:
```
/* Line 1
   Line 2
*/
```
Is there a way to put that Line 1 in a new line? If not, it's a highly recommended feature now.
- ...and hopefully more. I'll add'em here later.

None of such features are mentioned in the doc. I mean, you call it a wiki, right? A wiki shouldn't consist only of method names and brief introductions with a few words, should it? Shouldn't there be some basic demonstrations and examples, both for GUI configuring AND for file configuring?

**Comment by shedaniel** [comment]
First, the comment annotation is provided by the Jankson serialisation library, I don't manage how it handles comments. The specialty of this annotation is documented in the wiki.

Second, a friendlier tone would get you further than what you have right here, AutoConfig is provided free of charge, without any warranty, I do not work for you and neither do I have any responsibility to. You are free to use other configuration libraries if AutoConfig does not fit your requirements, as with many other people.

Third, the current wiki covers both configuration screen creation and config file configuration, examples are provided, I am not writing you a complete demonstration because that's not the aim of the wiki.

**Comment by Kouchya** [comment]
- My IDE snippet shows it's a `me.shedaniel.cloth.clothconfig.shadowed.blue.endless.jankson.Comment`, so I thought you were coping with it. May be my fault for this.
- I found no examples of the annotations, nor how they work differently for GUIs and for files. At least not on the same page you introduced the annotations. Plus, a wiki is supposed to explain the features clearly. Most of the features may already be explained clearly in this wiki, but not those I mentioned.
- You can view this issue as a mere complaint and just ignore it. I'm gonna close it because I already managed to tell you how the current wiki may waste a modder's time. It's up to you whether to take it into account. And yes, it's nothing of responsibility. But just don't expect users to be friendly at all, especially when the issues they met are about (maybe deliberately) omissive docs instead of bugs in the code.
