### ISSUE TITLE
Add a method returning a ConfigScreenFactory (mod menu integration)

### ISSUE THREAD

**Issue by YanisBft** [shedaniel/AutoConfig#7]
Currently, the method used to generate a cloth config screen and integrate it with mod menu returns an `<Supplier<Screen>>`, and we can only use it in a depecrated mod menu api method, that is meant to be removed in 1.16 snapshots:
```java
public Optional<Supplier<Screen>> getConfigScreen(Screen screen) {
    return Optional.of(AutoConfig.getConfigScreen(Config.class, screen));
}
```
Would be nice to have a method returning a ConfigScreenFactory, to be able to use this method:
```java
public ConfigScreenFactory<?> getModConfigScreenFactory() {}
```

**Comment by shedaniel** [comment]
no, you can implement that lambda yourself
